//todo arquivo q termina com http 
//chama a extensao para fazer testes
//### -> mostra q é um novo teste
//separarpor uma linha o cabegalho do body

### Listar Produtos
GET https://localhost:7098/api/produto/listar

### Cadastrar produto

POST https://localhost:7098/api/produto/cadastrar
Content-Type: application/json

{
    "Nome" : "Produto S",
    "Descricao" : "Este é o Produto C, uma descrição detalhada sobre o produto.",
    "Preco" : 29.99,
    "categoryId": 1
}

### Buscar Produtos
GET https://localhost:7098/api/produto/buscar/2

### Deletar Produto
DELETE https://localhost:7098/api/produto/deletar/2